site_name: Dev Docs
docs_dir: ./docs
theme:
  name: material
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
